site_name: Shareable-Structured-Semantic Model (S3Model)
copyright: 'Copyright 2009 - 2023 Timothy W. Cook - All Rights Reserved.'
theme:
    name: material
    features:
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.footer
    logo: images/SmallLogo.png
    favicon: images/favicon.ico
    palette:
      scheme: slate
      font:
        text: Roboto
    highlightjs: true
    hljs_languages:
        - yaml
    



nav:
    - Home: 'index.md'
    - Reference Model: 'RM/index.md'
    - Tools: 'tools.md'
    - Contributing: 'Contributing.md'
    - Support: 'support.md'
    - Glossary: 'glossary.md'
    - License: 'LICENSE.md'

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/S3Model
    - icon: fontawesome/brands/github 
      link: https://github.com/twcook
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/timothywaynecook
    - icon: fontawesome/solid/paper-plane
      link: mailto:s3modeldata@gmail.com
  consent:
    title: Cookie consent
    description: >- 


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
            